import { Scenario } from "../types";
import { sharedEndings } from "./shared";

export const taxesScenario: Scenario = {
  id: "taxes",
  name: "Tax Season",
  who: "Joe Walker · 19 · Walmart cashier",
  desc: "It's almost April 15. A W-2, some cash gigs, and a choice about whether to tell the truth.",
  estimatedTime: "~12 decisions",
  startMoney: 1560,
  defaultName: "Joe Walker",
  accent: "#4ECDC4",
  startSceneId: "intro",
  scenes: {
    intro: {
      title: "April 14 · 11:47 PM",
      text: () =>
`You're a part-time Walmart cashier. Your mom keeps texting you tax tutorials. Your roommate Dev is asleep with a burrito on his chest.

Sixteen browser tabs open. One blinks: "GET YOUR REFUND IN 24 HOURS."

Your W-2: $1,560. You also did $400 of cash lawn work, $250 DJing a wedding (Venmo), and sold an old gaming PC for $600.

Tomorrow is the federal deadline.`,
      choices: [
        { label: "File with IRS Free File. Report the W-2 + $400 lawn cash. Skip the PC (sold at a loss) and the $250 gig.",
          kind: "good",
          feedback: "Free File is legit under ~$79k. Cash gigs over $400 are reportable. Personal items sold at a loss aren't taxable.",
          effects: { wellbeing: 10, law: -10, addFlags: ["filed_honestly"] }, nextId: "w4_fix" },
        { label: "File the W-2 only. The cash jobs are invisible.",
          kind: "mid",
          feedback: "IRS matches W-2s/1099s, not cash. Technically evasion on $400 — usually ignored. Usually.",
          effects: { wellbeing: 2, law: 5, addFlags: ["underreported"] }, nextId: "w4_fix" },
        { label: "Use TurboTax 'Free.' Click through the $89 upsells.",
          kind: "mid",
          feedback: "TurboTax Free is narrow. Any side income forces an upgrade. You paid for a return that should've been free.",
          effects: { money: -89, wellbeing: 1 }, nextId: "w4_fix" },
        { label: "'Rapid Refund' strip-mall place. $200 fee, advance same day.",
          kind: "mid",
          feedback: "Refund-advance loans eat fees. On a $200 refund you basically broke even to pay someone.",
          effects: { money: -200, wellbeing: 2 }, nextId: "w4_fix" },
        { label: "Don't file. You barely made anything.",
          kind: "bad",
          feedback: "Failure-to-file is 5%/month up to 25%. You probably had a refund — forfeit after 3 years.",
          effects: { wellbeing: -12, law: 20, addFlags: ["didnt_file"], schedule: [[3, "irs_letter"]] },
          nextId: "skipped_filing" },
        { label: "Let Uncle Ray file for you. Three fake kids. 70/30 split of the $6k refund.",
          kind: "bad",
          feedback: "Straight-up fraud. The IRS has automated matching — they find it.",
          effects: { money: 6000, wellbeing: -8, law: 45, addFlags: ["tax_fraud"], schedule: [[2, "irs_visit"]] },
          nextId: "fraud_refund" },
      ],
    },
    w4_fix: {
      title: "Two days later · Walmart break room",
      text: () => `Manager Rhonda slides a W-4 across the table. "You filled this as 'EXEMPT.' That's why nothing was withheld. Refile or I bump you to single-zero."`,
      choices: [
        { label: "Single, no dependents, no adjustments.",
          kind: "good", feedback: "Correct default for most 19-year-olds. Withholding now = no surprise bill later.",
          effects: { wellbeing: 5 }, nextId: "refund" },
        { label: "EXEMPT again. Bigger paychecks.",
          kind: "bad", feedback: "Only truly exempt if zero liability this year AND last. False claim = underpayment penalties.",
          effects: { wellbeing: -3, law: 8, schedule: [[4, "owe_irs"]] }, nextId: "refund" },
        { label: "Ask Rhonda what any of it means.",
          kind: "good", feedback: "30 seconds of feeling dumb > years of confusion. She's done this 22 years.",
          effects: { wellbeing: 6 }, nextId: "refund" },
        { label: "Copy what Dev put on his.",
          kind: "mid", feedback: "Dev claims four dependents and has zero. You'll find out in April.",
          effects: { wellbeing: -1 }, nextId: "refund" },
      ],
    },
    refund: {
      title: "A week later",
      text: () => `$112 refund lands. Dev waves an envelope at you. "Open enrollment. You're on your mom's insurance till 26, right?"`,
      choices: [
        { label: "Call mom. Confirm you're on her employer plan.",
          kind: "good", feedback: "ACA lets you stay on a parent's plan until 26. Two-minute call, zero dollars.",
          effects: { wellbeing: 6, addFlags: ["insured"] }, nextId: "car_trouble" },
        { label: "Sign up for $40/mo 'MediSave Plus' on Instagram.",
          kind: "bad", feedback: "That's a health-sharing ministry, not insurance. Unregulated. Denies claims.",
          effects: { money: -40, wellbeing: -4, addFlags: ["fake_insurance"] }, nextId: "car_trouble" },
        { label: "Skip it. You're young and invincible.",
          kind: "mid", feedback: "One ER visit wipes that logic out.",
          effects: { wellbeing: -2, addFlags: ["uninsured"] }, nextId: "car_trouble" },
        { label: "Marketplace Bronze plan ($0 premium at your income).",
          kind: "good", feedback: "At your AGI you'd qualify for Medicaid in most states. Bronze works too.",
          effects: { wellbeing: 7, addFlags: ["insured"] }, nextId: "car_trouble" },
      ],
    },
    skipped_filing: {
      title: "Three weeks later",
      text: () => `Nothing has happened. Obviously you got away with it. Your buddy offers you a 2009 Civic for $2,000 cash.`,
      choices: [
        { label: "Buy, register, liability insurance ($90/mo).",
          kind: "good", feedback: "Liability is required in 48 states.",
          effects: { money: -2090, wellbeing: 5, addFlags: ["has_car", "insured_car"] }, nextId: "car_trouble" },
        { label: "Buy. Skip insurance and registration.",
          kind: "bad", feedback: "Driving uninsured is a misdemeanor. Unregistered = ticket waiting.",
          effects: { money: -2000, wellbeing: -5, law: 15, addFlags: ["has_car", "no_insurance_car"], schedule: [[2, "traffic_stop"]] },
          nextId: "car_trouble" },
        { label: "Pass. Can't afford it.",
          kind: "mid", feedback: "Responsible but limits your job options.",
          effects: { wellbeing: 1 }, nextId: "car_trouble" },
      ],
    },
    fraud_refund: {
      title: "Two weeks later",
      text: () => `$6,000 hit your account. Uncle Ray wants his $2,000 cut. You feel like a king. A very nervous king.`,
      choices: [
        { label: "Pay him. Blow the rest on a PS5, sneakers, DoorDash.",
          kind: "bad", feedback: "Spent evidence is still evidence.",
          effects: { money: -5500, wellbeing: -5 }, nextId: "car_trouble" },
        { label: "Pay him. Stash the rest.",
          kind: "mid", feedback: "You still committed fraud. Hiding it doesn't undo it.",
          effects: { money: -2000, wellbeing: -3 }, nextId: "car_trouble" },
        { label: "Call the IRS. Admit the fraud. Offer to pay it back.",
          kind: "good", feedback: "Voluntary disclosure massively reduces penalties. Brave call.",
          effects: { money: -6000, wellbeing: 10, law: -50, rmFlags: ["tax_fraud"] }, nextId: "car_trouble" },
      ],
    },
    car_trouble: {
      title: "A month later · Tuesday 7:42 AM",
      text: () => `Running late. Light turns yellow. You gun it. Blue lights. Immediately.\n\n"License and registration."`,
      choices: [
        { label: "Hand them over. 'Yes sir, no sir.' Take the ticket.",
          kind: "good", feedback: "Polite compliance + signing (not admitting) is the playbook.",
          effects: { money: -175, wellbeing: 2 }, nextId: "jury_duty" },
        { label: "Argue the light was 'clearly still yellow.' Demand a supervisor.",
          kind: "mid", feedback: "Roadside is the worst venue to exercise your rights. Fight it in court.",
          effects: { money: -175, wellbeing: -3 }, nextId: "jury_duty" },
        { label: "Speed off.",
          kind: "bad", feedback: "Felony evading. Every other flag just got worse.",
          effects: { wellbeing: -15, law: 40, addFlags: ["evaded_police"], schedule: [[1, "warrant"]] },
          nextId: "jury_duty" },
        { label: "Consent to a full vehicle search.",
          kind: "mid", feedback: "'I do not consent to searches' is a full sentence.",
          effects: { money: -175, wellbeing: 1 }, nextId: "jury_duty" },
      ],
    },
    jury_duty: {
      title: "Six weeks later",
      text: () => `JURY SUMMONS. Report Monday at 8 AM or face contempt.`,
      choices: [
        { label: "Show up. Sit for 6 hours. Get dismissed.",
          kind: "good", feedback: "Civic duty. Employers must legally give time off.",
          effects: { wellbeing: 4 }, nextId: "credit" },
        { label: "Ignore it. Trash it.",
          kind: "bad", feedback: "Failure to appear = bench warrant. Fines up to $1,000.",
          effects: { wellbeing: -10, law: 20, addFlags: ["missed_jury"], schedule: [[2, "warrant"]] },
          nextId: "credit" },
        { label: "Request a postponement online.",
          kind: "good", feedback: "Totally legit. Most courts allow it with a few clicks.",
          effects: { wellbeing: 3 }, nextId: "credit" },
        { label: "Show up dressed as a clown to get dismissed.",
          kind: "mid", feedback: "Technically civic duty. Judge was not amused.",
          effects: { wellbeing: 1 }, nextId: "credit" },
      ],
    },
    credit: {
      title: "A few months in",
      text: () => `Mail: 'PRE-APPROVED! 29.99% APR, $500 limit.' Also: secured card ($200 deposit, reports to all 3 bureaus).`,
      choices: [
        { label: "Secured card. Charge gas. Pay in full every month.",
          kind: "good", feedback: "Fastest legit way to build credit at 19.",
          effects: { money: -200, wellbeing: 6, addFlags: ["building_credit"] }, nextId: "side_hustle" },
        { label: "29.99% card. Max it on furniture.",
          kind: "bad", feedback: "Minimum payments at 29.99% = years of interest. Classic trap.",
          effects: { money: 500, wellbeing: -8, addFlags: ["credit_card_debt"] }, nextId: "side_hustle" },
        { label: "Neither. Cash only forever.",
          kind: "mid", feedback: "No credit history = hard to rent or finance a car.",
          effects: { wellbeing: -1 }, nextId: "side_hustle" },
        { label: "Authorized user on mom's 20-year-old card.",
          kind: "good", feedback: "Inherits her history. Legal, effective, free.",
          effects: { wellbeing: 5, addFlags: ["building_credit"] }, nextId: "side_hustle" },
      ],
    },
    side_hustle: {
      title: "Four months later",
      text: () => `Cousin Marco wants you to deposit checks 'for him.' 10% per check. Calls it 'invoice processing.'`,
      choices: [
        { label: "Do it. Easy money.",
          kind: "bad", feedback: "Mule scheme. Wire fraud + laundering. Account frozen; charges follow.",
          effects: { money: 400, wellbeing: -8, law: 50, addFlags: ["money_mule"], schedule: [[2, "fbi_visit"]] },
          nextId: "healthcare" },
        { label: "Decline. Hard no.",
          kind: "good", feedback: "Anyone asking to run money through your account is scamming or using you.",
          effects: { wellbeing: 7 }, nextId: "healthcare" },
        { label: "Agree 'just once.'",
          kind: "bad", feedback: "One deposit is enough for charges.",
          effects: { money: 40, wellbeing: -6, law: 35, addFlags: ["money_mule"], schedule: [[3, "fbi_visit"]] },
          nextId: "healthcare" },
        { label: "Report him to the bank's fraud line.",
          kind: "good", feedback: "Harsh but right. Banks log this. You're protected.",
          effects: { wellbeing: 6 }, nextId: "healthcare" },
      ],
    },
    healthcare: {
      title: "Saturday · 2 AM",
      text: () => `You slice your hand open chopping onions. Won't stop bleeding.`,
      choices: [
        { label: "Urgent care (~$150 insured, $300 not).",
          kind: "good", feedback: "Right call for non-life-threatening. ER is 5-10x more.",
          effects: { money: -200, health: -3, wellbeing: 3 }, nextId: "retirement" },
        { label: "ER. You want the 'real' doctors.",
          kind: "mid", feedback: "Stitches in ER = $1,500-3,000.",
          effects: { money: -1500, health: -2 }, nextId: "retirement" },
        { label: "Superglue and a paper towel. YouTube said.",
          kind: "bad", feedback: "Sometimes works. Sometimes a tendon infection.",
          effects: { health: -15, wellbeing: -5 }, nextId: "retirement" },
        { label: "Nurse hotline first (free with most insurance).",
          kind: "good", feedback: "Triage calls are free. Underused.",
          effects: { money: -200, health: -2, wellbeing: 5 }, nextId: "retirement" },
      ],
    },
    retirement: {
      title: "Promotion · payroll onboarding",
      text: () => `Promoted. $42k/year. HR slides a 401(k) form. 100% match up to 4%.`,
      choices: [
        { label: "4% contribution. Free $1,680/year in match.",
          kind: "good", feedback: "Match = 100% instant return.",
          effects: { wellbeing: 10, addFlags: ["retirement_started"] }, nextId: "finale" },
        { label: "0%. 'I'll start when I'm older.'",
          kind: "bad", feedback: "Starting at 30 vs 19 costs ~$300k by retirement.",
          effects: { wellbeing: -5 }, nextId: "finale" },
        { label: "15%. Max aggressively.",
          kind: "mid", feedback: "Admirable, but your budget will hurt. 4-6% early is the sweet spot.",
          effects: { wellbeing: 4, addFlags: ["retirement_started"] }, nextId: "finale" },
        { label: "Ask HR about Roth vs Traditional.",
          kind: "good", feedback: "At low income, Roth usually wins. Asking is 80% of the battle.",
          effects: { wellbeing: 8, addFlags: ["retirement_started"] }, nextId: "finale" },
      ],
    },

    // Delayed consequence scenes
    irs_letter: {
      title: "A letter arrives",
      text: () => `IRS Notice CP59. 'We have no record of your return.' $340 in penalties + interest.`,
      choices: [
        { label: "File immediately. Pay. Apologize.",
          kind: "good", feedback: "Penalties stop accruing the day you file.",
          effects: { money: -340, wellbeing: 2, law: -30, rmFlags: ["didnt_file"] }, nextId: null },
        { label: "Throw it away.",
          kind: "bad", feedback: "The IRS does not forget.",
          effects: { wellbeing: -8, law: 20, schedule: [[3, "irs_visit"]] }, nextId: null },
      ],
    },
    irs_visit: {
      title: "Knock knock",
      text: () => `Two IRS agents at your door. They know. They want to talk.`,
      choices: [
        { label: "Cooperate. Ask for a payment plan.",
          kind: "good", feedback: "Installment agreements exist. Cooperation usually avoids criminal referral.",
          effects: { money: -3000, wellbeing: -2, law: -50, rmFlags: ["tax_fraud"] }, nextId: null },
        { label: "Slam door. Pack a bag. Drive to Vancouver.",
          kind: "bad", feedback: "You're now a fugitive. The border has cameras.",
          effects: { wellbeing: -20, law: 30, addFlags: ["fugitive"], schedule: [[4, "vancouver_knock"]] }, nextId: null },
        { label: "Lawyer up.",
          kind: "good", feedback: "A tax attorney costs $2k but saves you from prison.",
          effects: { money: -2000, wellbeing: 3, law: -40 }, nextId: null },
      ],
    },
    vancouver_knock: {
      title: "Vancouver · 6 months later",
      text: () => `You thought you were safe. RCMP has a provisional warrant.`,
      choices: [
        { label: "Surrender.", kind: "mid", feedback: "Extradition + cooperation still beats running.",
          effects: { wellbeing: -10, rmFlags: ["fugitive"] }, nextId: "ending_jail" },
        { label: "Run again.", kind: "bad", feedback: "You are 19 and broke.",
          effects: { wellbeing: -30 }, nextId: "ending_fugitive" },
      ],
    },
    traffic_stop: {
      title: "Flashing lights",
      text: () => `You're uninsured and unregistered. Routine stop.`,
      choices: [
        { label: "Honest. Accept the tow and tickets.",
          kind: "mid", feedback: "Painful but survivable. ~$1,200 total.",
          effects: { money: -1200, wellbeing: -4, rmFlags: ["no_insurance_car"] }, nextId: null },
        { label: "Flee.", kind: "bad", feedback: "Pursuit. Escalates fast.",
          effects: { wellbeing: -20, law: 50, addFlags: ["evaded_police"], schedule: [[1, "warrant"]] }, nextId: null },
      ],
    },
    warrant: {
      title: "Warrant issued",
      text: () => `Active warrant. Surfaces at the next stop, airport, or background check.`,
      choices: [
        { label: "Turn yourself in with a lawyer.",
          kind: "good", feedback: "Voluntary surrender + counsel = lower bail, better plea.",
          effects: { money: -2000, wellbeing: 2, law: -40, rmFlags: ["evaded_police", "missed_jury"] }, nextId: null },
        { label: "Keep living like nothing's wrong.",
          kind: "bad", feedback: "Works until it doesn't.",
          effects: { wellbeing: -15, law: 20, schedule: [[3, "arrest"]] }, nextId: null },
      ],
    },
    fbi_visit: {
      title: "FBI at your door",
      text: () => `Financial Crimes Task Force. Bank records, Marco's records, your texts.`,
      choices: [
        { label: "Cooperate. Testify against Marco.",
          kind: "mid", feedback: "Cooperation agreements exist. Record stays, prison usually doesn't.",
          effects: { wellbeing: -10, rmFlags: ["money_mule"], addFlags: ["felony_record"] }, nextId: null },
        { label: "Say nothing. Lawyer up.",
          kind: "good", feedback: "Never talk to federal agents without an attorney.",
          effects: { money: -5000, wellbeing: -2, law: -30, rmFlags: ["money_mule"] }, nextId: null },
        { label: "Try to explain it away.",
          kind: "bad", feedback: "Lying to a federal agent = 18 USC 1001. Separate felony.",
          effects: { wellbeing: -18, schedule: [[1, "arrest"]] }, nextId: null },
      ],
    },
    owe_irs: {
      title: "April rolls around",
      text: () => `You claimed EXEMPT. Nothing withheld. You owe $1,100.`,
      choices: [
        { label: "Set up an IRS installment plan.",
          kind: "good", feedback: "Low-interest, automatic, saves your credit.",
          effects: { money: -200, wellbeing: 2, law: -20 }, nextId: null },
        { label: "Ignore it.",
          kind: "bad", feedback: "Wage garnishment incoming.",
          effects: { wellbeing: -15, law: 25, schedule: [[3, "irs_visit"]] }, nextId: null },
      ],
    },
    arrest: {
      title: "Arrested",
      text: () => `Handcuffs. Booking. A public defender with 80 other cases.`,
      choices: [
        { label: "Take the plea.", kind: "mid", feedback: "Most cases end in pleas.",
          effects: { wellbeing: -10, addFlags: ["felony_record"] }, nextId: "ending_jail" },
      ],
    },

    ending_good: {
      title: "YOU GREW UP",
      text: s => `${s.charName}, five years later. Employed. Insured. Credit score 740. Retirement compounding in the background.\n\nNo one throws a parade for this. That's adulthood.`,
      ending: true, endingKind: "good",
    },
    ending_mid: {
      title: "GETTING BY",
      text: s => `${s.charName}. Still renting. Still nervous about government mail. Free, employed, learning.\n\nMost people's real ending.`,
      ending: true, endingKind: "mid",
    },
    ending_bad: {
      title: "IT ALL CAUGHT UP",
      text: s => `${s.charName}. Wage garnishment. Tanked credit. Every future application asks about the record.\n\nIgnoring the letters was the worst possible trade.`,
      ending: true, endingKind: "bad",
    },
    ...sharedEndings,

    finale: {
      title: "Five years later",
      text: () => `You're 24. Let's see how it played out.`,
      choices: [
        { label: "Continue...", kind: "mid", feedback: "",
          next: s => {
            if (s.flags.has("fugitive")) return "ending_fugitive";
            if (s.flags.has("felony_record")) return "ending_jail";
            if (s.law >= 70) return "ending_bad";
            if (s.wellbeing >= 70 && !s.flags.has("tax_fraud")) return "ending_good";
            return "ending_mid";
          }
        },
      ],
    },
  },
};
