uploads = []
outputs = []

[[generated]]
id = "pFfyIJRD-1W8F8rKi1gqC"
uri = "file://artifacts/adulting-app/assets/images/icon.png"
type = "image"
title = "adulting app icon"

[[generated]]
id = "vSlvl2W_YLJmaMfzRt06b"
uri = "file://artifacts/adulting-app/assets/images/money-track.png"
type = "image"
title = "money track hero"

[[generated]]
id = "Z0cnb_j_peV6ufqZWh31l"
uri = "file://artifacts/adulting-app/assets/images/tax-track.png"
type = "image"
title = "tax track hero"
